language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - henrylee2cn@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://github.com/henrylee2cn/erpc-book
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@github.com/henrylee2cn/erpc-book" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/henrylee2cn/erpc-book.git # 设置 github 地址
